name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 2. Sätter upp Java
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    #- name: Run Tests
     # run: mvn clean test

    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME}}/cloudstore-backend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloudstore-backend:latest

  deploy:
     needs: build-and-push
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Prepare deployment
         run: cp Dockerrun.aws.json deploy.zip

    # 5. Ladda upp och distribuera till Elastic Beanstalks
       - name: Deploy to Elastic Beanstalk
         uses: einaregilsson/beanstalk-deploy@v22
         with:
           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           application_name: 'cloudstore-backend'
           environment_name: 'Cloudstorebackend-env'
           version_label: 'deploy-${{ github.sha }}'
           region: eu-north-1
           deployment_package: deploy.zip
